version: '3.5'
services:
    nginx:
        image: nginx:latest
        container_name: soapbox_nginx
        working_dir: /code
        tty: true
        links:
            - fpm
        ports:
            - "80:80"
        volumes:
            - .:/code
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
    fpm:
        build:
            context: ./docker/
            args:
                - "INSTALL_XDEBUG=false"
        container_name: soapbox_fpm
        working_dir: /code
        user: ${CURRENT_UID}
        tty: true
        volumes:
            - .:/code
            - ./docker/php-docker.ini:/usr/local/etc/php/conf.d/php-docker.ini
    node:
        image: node:14
        container_name: soapbox_node
        command: npm run watch
        working_dir: /app
        tty: true
        volumes:
         - .:/app
    mysql:
      image: mysql:8
      container_name: soapbox_mysql
      command: --default-authentication-plugin=mysql_native_password
      tty: true
      environment:
        - "MYSQL_ROOT_PASSWORD=secret"
        - "MYSQL_DATABASE=soapbox"
        - "MYSQL_USER=soapbox"
        - "MYSQL_PASSWORD=secret"
      volumes:
        - soapbox-datavolume:/var/lib/mysql
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: soapbox_pma
      ports:
        - "8989:80"
      environment:
        - "PMA_HOST=mysql"
        - "PMA_PORT=3306"
volumes:
    soapbox-datavolume:
